// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOVI3gTj4YQV_a4mSJaJFMQBxwF7a-9Y',
    appId: '1:387345046989:web:a9b31829f51d4af739f884',
    messagingSenderId: '387345046989',
    projectId: 'fierabase-test',
    authDomain: 'fierabase-test.firebaseapp.com',
    databaseURL: 'https://fierabase-test-default-rtdb.firebaseio.com',
    storageBucket: 'fierabase-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzBA-C_VKNFRUcqSyvFoyZv-Ym7v1UqM',
    appId: '1:387345046989:android:8cadd62901e8e69139f884',
    messagingSenderId: '387345046989',
    projectId: 'fierabase-test',
    databaseURL: 'https://fierabase-test-default-rtdb.firebaseio.com',
    storageBucket: 'fierabase-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJoVUQCHIMMC0R456bknbEFvqEnWqHSV4',
    appId: '1:387345046989:ios:1645f98e2e3f96fd39f884',
    messagingSenderId: '387345046989',
    projectId: 'fierabase-test',
    databaseURL: 'https://fierabase-test-default-rtdb.firebaseio.com',
    storageBucket: 'fierabase-test.appspot.com',
    iosClientId: '387345046989-ji9cu4m4ehqie410vlfan9fibu7ahm79.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJoVUQCHIMMC0R456bknbEFvqEnWqHSV4',
    appId: '1:387345046989:ios:1645f98e2e3f96fd39f884',
    messagingSenderId: '387345046989',
    projectId: 'fierabase-test',
    databaseURL: 'https://fierabase-test-default-rtdb.firebaseio.com',
    storageBucket: 'fierabase-test.appspot.com',
    iosClientId: '387345046989-ji9cu4m4ehqie410vlfan9fibu7ahm79.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
